var options = {
    solution: 			[[null,	 null,	null,	null,	null,	'P',	null,	null,	null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null],
                         [null,  null,	null,	null,	null,	'R',	null,	null,	null,	null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null],
                         [null,  'Q',	null,	null,	null,	'E',	null,	null,	null,	null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null],
                         [null,  'U',	null,	null,	null,	'I',	null,	null,	null,	null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null],
                         [null,  'A',	'U',	'T',	'O',	'G',	'Y',	'R',	'O',	null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null],
                         [null,  'D',	null,	null,	null,	'N',	null,	null,	null,   null,	null,   null,   null,   null,   null,   null,   null,   null,   null,   null],
                         [null,  'R',	null,	null,	null,	'I',	null,	null,	null,	null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null],
                         [null,  'A',	null,	null,	null,	'T',	'R',	'A',	'N',	'S',    'P',    'O',    'N',    'D',    'E',    'R',    null,   null,   null,   null],
                         [null,  'P',	null,	null,	null,	'I',	null,	null,	null,	null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null],
                         [null,	 'L',	null,	null,	null,	'O',	'V',	'E',	'R',    'S',    'H',    'O',    'O',    'T',    'A',    'R',    'M',    'A',    'C',    null],
                         [null,	 'A',	null,	null,	null,	'N',	'A',	'V',	'A',    'I',    'D',    null,   'B',    null,   null,   null,   'T',    null,   null,   null],
                         [null,	 'N',	null,	null,	null,	null,	null,	null,	'I',    null,   null,   null,   'O',    null,   null,   null,   'O',    null,   null,   null],
                         [null,	 'E',	null,	null,	null,	null,	null,	null,	'R',    null,   null,   null,   'G',    null,   'J',    null,   'W',    null,   null,   null],
                         [null,	 null,	null,	null,	null,	null,	null,	null,	'F',    'L',    'A',    'P',    'E',    'R',    'O',    'N',    null,   null,   null,   null],
                         [null,	 null,	null,	null,	null,	null,	null,	null,	'O',    null,   null,   null,   'Y',    null,   'Y',    'O',    'K',    'E',    null,   null],
                         [null,	 null,	null,	null,	null,	null,	null,	null,	'I',    null,   null,   null,   null,   null,   'S',    'Q',    'U',    'A',    'W',    'K' ],
                         [null,	 null,	null,	null,	null,	null,	null,	null,	'L',    null,   null,   null,   null,   null,   'T',    null,   null,   null,   null,   'N' ],
                         [null,	 null,	null,	null,	null,	null,	null,	null,	null,   null,   null,   null,   null,   null,   'I',    null,   null,   null,   null,   'O' ],
                         [null,	 null,	null,	null,	null,	null,	null,	null,	null,   null,   null,   null,   null,   null,   'C',    null,   null,   null,   null,   'T' ],
                         [null,	 null,	null,	null,	null,	null,	null,	null,	null,   null,   null,   null,   null,   null,   'K',    null,   null,   null,   null,   null]],


     index: 			[[null,   null,   null,   null,   null,      2,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null],
                         [null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null],
                         [null,      1,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null],
                         [null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null],
                         [null,      8,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null],
                         [null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null],
                         [null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null],
                         [null,   null,   null,   null,   null,      9,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null],
                         [null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null],
                         [null,   null,   null,   null,   null,     10,   null,   null,   null,   null,   null,   null,   null,     11,   null,   null,      6,   null,   null,   null],
                         [null,   null,   null,   null,   null,     12,   null,   null,      3,   null,   null,   null,      4,   null,   null,   null,   null,   null,   null,   null],
                         [null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null],
                         [null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null,      5,   null,   null,   null,   null,   null],
                         [null,   null,   null,   null,   null,   null,   null,   null,     13,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null],
                         [null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null,     14,   null,   null,   null,   null,   null],
                         [null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null,     15,   null,   null,   null,   null,      7],
                         [null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null],
                         [null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null],
                         [null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null],
                         [null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null]],

  questions_across: [	   "1. A type of aircraft that has four or more wings of similar span",
                           "2. Ignition that takes place in an internal combustion engine before the usual ignition occurs",
                           "3. The shape of a surface such as a wing, blade, turbine or rotor that generates lift from air passing over it",
                           "4. An unknown radar contact, usually non-friendly",
                           "5. The main device found in the cockpit to control the aircraft",
                           "6. Maximum takeoff weight",
                           "7. A measurement or unit of speed that equals one nautical mile and about 1.15 statute miles"],

  questions_down: [		  "8. An aircraft which is often wingless, similar to a helicopter",
                          "9. A device carried in an airplane which produces a coded pattern which is recognized on an air traffic control radar screen",
                          "10. Landing an aircraft beyond the runway",
                          "11. The paved area of an airport, where aircrafts are parked, fuelled, loaded and unloaded",
                          "12. A device in an aircraft used to help with navigation",
                          "13. A control surface that uses aspects of both flaps and ailerons",
                          "14. The control wheel of an aircraft, similar to a steering wheel",
                          "15. A four digit number assigned to an aircraft. The pilot can use this to identify his/her plane while contacting ATC"]

};


cwp_nmsp.activateCWP(document.getElementById("myPuzzle"),false,options);